### ISSUE TITLE
Excessive Prints to Debugger Console 

### ISSUE THREAD

**Issue by ameirson** [bat52/cheap_pie#3]
Observed at version 1.0.2 installed from PyPi.

The recently added visual representation of register fields through __repr__ function cause excessive prints to debugger console making it very difficult to use.
While the prints are nice on their own, I believe they should not reach debugger console.

![cheap-pie](https://github.com/bat52/cheap_pie/assets/72041929/adcf582b-35ba-4a38-8d04-7f12f0b8f475)

**Comment by bat52** [comment]
I had asked myself if the wavedrom print would get in the way, but it was so good looking that I wanted to see it in the first place.
Yet, per se it is not terribly useful. I have moved it in the help method instead, and released on pypi as version 1.0.3 .

**Comment by ameirson** [comment]
Thanks for the quick support.
